### PR TITLE
Media updates

### PR DESCRIPTION
**Pull request by ncphillips**
- [x] Waiting on tinacms/tinacms release

### CODE REVIEW

**Review by kendallstrautman — APPROVED** [review]

**Comment by DirtyF** [comment]
I get the following error when trying to upload an image through the media manager screen plugin:

```
index.js:1 Fetch finished loading: POST "http://localhost:8000/___tina/upload".
n.writeMediaToDisk @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
s @ index.js:1
h.persist @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
c @ index.js:1
l.persist @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
onDrop @ index.js:1
(anonymous) @ index.js:656
Promise.then (async)
(anonymous) @ index.js:607
(anonymous) @ index.js:152
(anonymous) @ index.js:150
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:293
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:307
executeDispatch @ react-dom.development.js:390
executeDispatchesInOrder @ react-dom.development.js:415
executeDispatchesAndRelease @ react-dom.development.js:3279
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3288
forEachAccumulated @ react-dom.development.js:3260
runEventsInBatch @ react-dom.development.js:3305
runExtractedPluginEventsInBatch @ react-dom.development.js:3515
handleTopLevel @ react-dom.development.js:3559
batchedEventUpdates$1 @ react-dom.development.js:21872
batchedEventUpdates @ react-dom.development.js:796
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3569
attemptToDispatchEvent @ react-dom.development.js:4268
dispatchEvent @ react-dom.development.js:4190
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
discreteUpdates$1 @ react-dom.development.js:21888
discreteUpdates @ react-dom.development.js:807
dispatchDiscreteEvent @ react-dom.development.js:4169
index.js:1 Uncaught (in promise) Error: Not implemented
    at h.<anonymous> (index.js:1)
    at index.js:1
    at Object.next (index.js:1)
    at index.js:1
    at new Promise (<anonymous>)
    at s (index.js:1)
    at h.list (index.js:1)
    at l.<anonymous> (index.js:1)
    at index.js:1
    at Object.next (index.js:1)
    at index.js:1
    at new Promise (<anonymous>)
    at c (index.js:1)
    at l.list (index.js:1)
    at u.n [as callback] (index.js:1)
    at u.handleEvent (index.js:1)
    at index.js:1
    at Array.forEach (<anonymous>)
    at s.dispatch (index.js:1)
    at l.<anonymous> (index.js:1)
    at index.js:1
    at Object.next (index.js:1)
    at n (index.js:1)
```

**Comment by kendallstrautman** [comment]
We may need to pre-release the git-media-store updates for that @DirtyF

**Comment by ncphillips** [comment]
Just did that pre-release and tested. Listing and uploading seems to work

**Comment by DirtyF** [comment]
List, upload, delete, and swap an image works fine 🎉 
https://www.loom.com/share/83eb43fffcdd4771ac746912c2f15b8a

**Pull request merged**
